name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Install Allure globally
          run: npm install -g allure-commandline
        - name: Test
          run: npm run test
        - name: Generate report
          run: allure generate allure-results/ --clean
        - name: Upload Test Results Report
          uses: actions/upload-artifact@v2.3.1
          with:
            name: allure-report
            path: allure-report
        - name: Test marketplace action
          uses: simple-elf/allure-report-action@master
          if: always()
          id: allure-report
          with:
            allure_results: build/allure-results
            gh_pages: gh-pages
            allure_report: allure-report
            allure_history: allure-history
