name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.3.0
        - name: Install
          run: npm install
        - name: Test
          run: npm run test
        - name: Generate report
          run: allure generate allure-results/ --clean
        - uses: actions/upload-artifact@v2
          if: failure()
          with:
            name: allure-report
            path: allure-report
